"""add user_settings table

Revision ID: 2e733f087366
Revises: e5d4e4929685
Create Date: 2026-07-22 06:37:00.879545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e733f087366'
down_revision: Union[str, None] = 'e5d4e4929685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_voice', sa.String(length=50), nullable=False),
    sa.Column('stt_language', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
